BEGIN;
-- Data provinsi (38 baris)
INSERT INTO public.provinsi (kode, nama, ibukota, zona_waktu, pulau, latitude, longitude) VALUES
  ('11', 'Aceh', 'Kota Banda Aceh', 'WIB', 'Sumatera', 4.695135, 96.749399),
  ('12', 'Sumatera Utara', 'Kota Medan', 'WIB', 'Sumatera', 2.115355, 99.545097),
  ('13', 'Sumatera Barat', 'Kota Padang', 'WIB', 'Sumatera', -0.73994, 100.800005),
  ('14', 'Riau', 'Kota Pekanbaru', 'WIB', 'Sumatera', 0.293347, 101.706829),
  ('15', 'Jambi', 'Kota Jambi', 'WIB', 'Sumatera', -1.485183, 102.438058),
  ('16', 'Sumatera Selatan', 'Kota Palembang', 'WIB', 'Sumatera', -3.319437, 104.914703),
  ('17', 'Bengkulu', 'Kota Bengkulu', 'WIB', 'Sumatera', -3.577847, 102.346388),
  ('18', 'Lampung', 'Kota Bandar Lampung', 'WIB', 'Sumatera', -4.558585, 105.406808),
  ('19', 'Kepulauan Bangka Belitung', 'Kota Pangkalpinang', 'WIB', 'Sumatera', -2.741051, 106.440587),
  ('21', 'Kepulauan Riau', 'Kota Tanjungpinang', 'WIB', 'Sumatera', 3.945651, 108.142867),
  ('31', 'Daerah Khusus Ibukota Jakarta', 'Kota Jakarta Pusat', 'WIB', 'Jawa', -6.208763, 106.845599),
  ('32', 'Jawa Barat', 'Kota Bandung', 'WIB', 'Jawa', -6.917464, 107.619123),
  ('33', 'Jawa Tengah', 'Kota Semarang', 'WIB', 'Jawa', -7.150975, 110.140259),
  ('34', 'Daerah Istimewa Yogyakarta', 'Kota Yogyakarta', 'WIB', 'Jawa', -7.79558, 110.36949),
  ('35', 'Jawa Timur', 'Kota Surabaya', 'WIB', 'Jawa', -7.536064, 112.238402),
  ('36', 'Banten', 'Kota Serang', 'WIB', 'Jawa', -6.405817, 106.064018),
  ('51', 'Bali', 'Kota Denpasar', 'WITA', 'Bali & Nusa Tenggara', -8.409518, 115.188916),
  ('52', 'Nusa Tenggara Barat', 'Kota Mataram', 'WITA', 'Bali & Nusa Tenggara', -8.652933, 117.361648),
  ('53', 'Nusa Tenggara Timur', 'Kota Kupang', 'WITA', 'Bali & Nusa Tenggara', -8.657382, 121.07937),
  ('61', 'Kalimantan Barat', 'Kota Pontianak', 'WIB', 'Kalimantan', -0.278781, 111.475285),
  ('62', 'Kalimantan Tengah', 'Kota Palangkaraya', 'WIB', 'Kalimantan', -1.681488, 113.382354),
  ('63', 'Kalimantan Selatan', 'Kota Banjarbaru', 'WITA', 'Kalimantan', -3.092642, 115.283758),
  ('64', 'Kalimantan Timur', 'Kota Samarinda', 'WITA', 'Kalimantan', 0.538659, 116.419389),
  ('65', 'Kalimantan Utara', 'Tanjung Selor', 'WITA', 'Kalimantan', 2.725947, 116.293444),
  ('71', 'Sulawesi Utara', 'Kota Manado', 'WITA', 'Sulawesi', 0.624693, 123.975002),
  ('72', 'Sulawesi Tengah', 'Kota Palu', 'WITA', 'Sulawesi', -1.430025, 121.445618),
  ('73', 'Sulawesi Selatan', 'Kota Makassar', 'WITA', 'Sulawesi', -3.668799, 119.974053),
  ('74', 'Sulawesi Tenggara', 'Kota Kendari', 'WITA', 'Sulawesi', -4.14491, 122.174605),
  ('75', 'Gorontalo', 'Kota Gorontalo', 'WITA', 'Sulawesi', 0.699937, 122.446724),
  ('76', 'Sulawesi Barat', 'Mamuju', 'WITA', 'Sulawesi', -2.844137, 119.232078),
  ('81', 'Maluku', 'Kota Ambon', 'WIT', 'Maluku', -3.238462, 130.145273),
  ('82', 'Maluku Utara', 'Sofifi', 'WIT', 'Maluku', 1.570999, 127.808769),
  ('91', 'Papua', 'Kota Jayapura', 'WIT', 'Papua', -4.269928, 138.080353),
  ('92', 'Papua Barat', 'Manokwari', 'WIT', 'Papua', -1.336115, 133.174716),
  ('93', 'Papua Selatan', 'Salor (Merauke)', 'WIT', 'Papua', -7.5, 139.5),
  ('94', 'Papua Tengah', 'Nabire', 'WIT', 'Papua', -3.5, 136),
  ('95', 'Papua Pegunungan', 'Wamena', 'WIT', 'Papua', -4.1, 138.9),
  ('96', 'Papua Barat Daya', 'Kota Sorong', 'WIT', 'Papua', -1, 132)
ON CONFLICT (kode) DO NOTHING;

-- Data kabupaten_kota (514 baris)
INSERT INTO public.kabupaten_kota (kode, provinsi_kode, tipe, nama, ibukota, zona_waktu, latitude, longitude) VALUES
  ('11.01', '11', 'KABUPATEN', 'Kabupaten Aceh Selatan', NULL, 'WIB', NULL, NULL),
  ('11.02', '11', 'KABUPATEN', 'Kabupaten Aceh Tenggara', NULL, 'WIB', NULL, NULL),
  ('11.03', '11', 'KABUPATEN', 'Kabupaten Aceh Timur', NULL, 'WIB', NULL, NULL),
  ('11.04', '11', 'KABUPATEN', 'Kabupaten Aceh Tengah', NULL, 'WIB', NULL, NULL),
  ('11.05', '11', 'KABUPATEN', 'Kabupaten Aceh Barat', NULL, 'WIB', NULL, NULL),
  ('11.06', '11', 'KABUPATEN', 'Kabupaten Aceh Besar', NULL, 'WIB', NULL, NULL),
  ('11.07', '11', 'KABUPATEN', 'Kabupaten Pidie', NULL, 'WIB', NULL, NULL),
  ('11.08', '11', 'KABUPATEN', 'Kabupaten Aceh Utara', NULL, 'WIB', NULL, NULL),
  ('11.09', '11', 'KABUPATEN', 'Kabupaten Simeulue', NULL, 'WIB', NULL, NULL),
  ('11.10', '11', 'KABUPATEN', 'Kabupaten Aceh Singkil', NULL, 'WIB', NULL, NULL),
  ('11.11', '11', 'KABUPATEN', 'Kabupaten Bireuen', NULL, 'WIB', NULL, NULL),
  ('11.12', '11', 'KABUPATEN', 'Kabupaten Aceh Barat Daya', NULL, 'WIB', NULL, NULL),
  ('11.13', '11', 'KABUPATEN', 'Kabupaten Gayo Lues', NULL, 'WIB', NULL, NULL),
  ('11.14', '11', 'KABUPATEN', 'Kabupaten Aceh Jaya', NULL, 'WIB', NULL, NULL),
  ('11.15', '11', 'KABUPATEN', 'Kabupaten Nagan Raya', NULL, 'WIB', NULL, NULL),
  ('11.16', '11', 'KABUPATEN', 'Kabupaten Aceh Tamiang', NULL, 'WIB', NULL, NULL),
  ('11.17', '11', 'KABUPATEN', 'Kabupaten Bener Meriah', NULL, 'WIB', NULL, NULL),
  ('11.18', '11', 'KABUPATEN', 'Kabupaten Pidie Jaya', NULL, 'WIB', NULL, NULL),
  ('11.71', '11', 'KOTA', 'Kota Banda Aceh', 'Kota Banda Aceh', 'WIB', NULL, NULL),
  ('11.72', '11', 'KOTA', 'Kota Sabang', 'Kota Sabang', 'WIB', NULL, NULL),
  ('11.73', '11', 'KOTA', 'Kota Lhokseumawe', 'Kota Lhokseumawe', 'WIB', NULL, NULL),
  ('11.74', '11', 'KOTA', 'Kota Langsa', 'Kota Langsa', 'WIB', NULL, NULL),
  ('11.75', '11', 'KOTA', 'Kota Subulussalam', 'Kota Subulussalam', 'WIB', NULL, NULL),
  ('12.01', '12', 'KABUPATEN', 'Kabupaten Tapanuli Tengah', NULL, 'WIB', NULL, NULL),
  ('12.02', '12', 'KABUPATEN', 'Kabupaten Tapanuli Utara', NULL, 'WIB', NULL, NULL),
  ('12.03', '12', 'KABUPATEN', 'Kabupaten Tapanuli Selatan', NULL, 'WIB', NULL, NULL),
  ('12.04', '12', 'KABUPATEN', 'Kabupaten Nias', NULL, 'WIB', NULL, NULL),
  ('12.05', '12', 'KABUPATEN', 'Kabupaten Langkat', NULL, 'WIB', NULL, NULL),
  ('12.06', '12', 'KABUPATEN', 'Kabupaten Karo', NULL, 'WIB', NULL, NULL),
  ('12.07', '12', 'KABUPATEN', 'Kabupaten Deli Serdang', NULL, 'WIB', NULL, NULL),
  ('12.08', '12', 'KABUPATEN', 'Kabupaten Simalungun', NULL, 'WIB', NULL, NULL),
  ('12.09', '12', 'KABUPATEN', 'Kabupaten Asahan', NULL, 'WIB', NULL, NULL),
  ('12.10', '12', 'KABUPATEN', 'Kabupaten Labuhanbatu', NULL, 'WIB', NULL, NULL),
  ('12.11', '12', 'KABUPATEN', 'Kabupaten Dairi', NULL, 'WIB', NULL, NULL),
  ('12.12', '12', 'KABUPATEN', 'Kabupaten Toba', NULL, 'WIB', NULL, NULL),
  ('12.13', '12', 'KABUPATEN', 'Kabupaten Mandailing Natal', NULL, 'WIB', NULL, NULL),
  ('12.14', '12', 'KABUPATEN', 'Kabupaten Nias Selatan', NULL, 'WIB', NULL, NULL),
  ('12.15', '12', 'KABUPATEN', 'Kabupaten Pakpak Bharat', NULL, 'WIB', NULL, NULL),
  ('12.16', '12', 'KABUPATEN', 'Kabupaten Humbang Hasundutan', NULL, 'WIB', NULL, NULL),
  ('12.17', '12', 'KABUPATEN', 'Kabupaten Samosir', NULL, 'WIB', NULL, NULL),
  ('12.18', '12', 'KABUPATEN', 'Kabupaten Serdang Bedagai', NULL, 'WIB', NULL, NULL),
  ('12.19', '12', 'KABUPATEN', 'Kabupaten Batu Bara', NULL, 'WIB', NULL, NULL),
  ('12.20', '12', 'KABUPATEN', 'Kabupaten Padang Lawas Utara', NULL, 'WIB', NULL, NULL),
  ('12.21', '12', 'KABUPATEN', 'Kabupaten Padang Lawas', NULL, 'WIB', NULL, NULL),
  ('12.22', '12', 'KABUPATEN', 'Kabupaten Labuhanbatu Selatan', NULL, 'WIB', NULL, NULL),
  ('12.23', '12', 'KABUPATEN', 'Kabupaten Labuhanbatu Utara', NULL, 'WIB', NULL, NULL),
  ('12.24', '12', 'KABUPATEN', 'Kabupaten Nias Utara', NULL, 'WIB', NULL, NULL),
  ('12.25', '12', 'KABUPATEN', 'Kabupaten Nias Barat', NULL, 'WIB', NULL, NULL),
  ('12.71', '12', 'KOTA', 'Kota Medan', 'Kota Medan', 'WIB', NULL, NULL),
  ('12.72', '12', 'KOTA', 'Kota Pematangsiantar', 'Kota Pematangsiantar', 'WIB', NULL, NULL),
  ('12.73', '12', 'KOTA', 'Kota Sibolga', 'Kota Sibolga', 'WIB', NULL, NULL),
  ('12.74', '12', 'KOTA', 'Kota Tanjungbalai', 'Kota Tanjungbalai', 'WIB', NULL, NULL),
  ('12.75', '12', 'KOTA', 'Kota Binjai', 'Kota Binjai', 'WIB', NULL, NULL),
  ('12.76', '12', 'KOTA', 'Kota Tebing Tinggi', 'Kota Tebing Tinggi', 'WIB', NULL, NULL),
  ('12.77', '12', 'KOTA', 'Kota Padangsidimpuan', 'Kota Padangsidimpuan', 'WIB', NULL, NULL),
  ('12.78', '12', 'KOTA', 'Kota Gunungsitoli', 'Kota Gunungsitoli', 'WIB', NULL, NULL),
  ('13.01', '13', 'KABUPATEN', 'Kabupaten Pesisir Selatan', NULL, 'WIB', NULL, NULL),
  ('13.02', '13', 'KABUPATEN', 'Kabupaten Solok', NULL, 'WIB', NULL, NULL),
  ('13.03', '13', 'KABUPATEN', 'Kabupaten Sijunjung', NULL, 'WIB', NULL, NULL),
  ('13.04', '13', 'KABUPATEN', 'Kabupaten Tanah Datar', NULL, 'WIB', NULL, NULL),
  ('13.05', '13', 'KABUPATEN', 'Kabupaten Padang Pariaman', NULL, 'WIB', NULL, NULL),
  ('13.06', '13', 'KABUPATEN', 'Kabupaten Agam', NULL, 'WIB', NULL, NULL),
  ('13.07', '13', 'KABUPATEN', 'Kabupaten Lima Puluh Kota', NULL, 'WIB', NULL, NULL),
  ('13.08', '13', 'KABUPATEN', 'Kabupaten Pasaman', NULL, 'WIB', NULL, NULL),
  ('13.09', '13', 'KABUPATEN', 'Kabupaten Kepulauan Mentawai', NULL, 'WIB', NULL, NULL),
  ('13.10', '13', 'KABUPATEN', 'Kabupaten Dharmasraya', NULL, 'WIB', NULL, NULL),
  ('13.11', '13', 'KABUPATEN', 'Kabupaten Solok Selatan', NULL, 'WIB', NULL, NULL),
  ('13.12', '13', 'KABUPATEN', 'Kabupaten Pasaman Barat', NULL, 'WIB', NULL, NULL),
  ('13.71', '13', 'KOTA', 'Kota Padang', 'Kota Padang', 'WIB', NULL, NULL),
  ('13.72', '13', 'KOTA', 'Kota Solok', 'Kota Solok', 'WIB', NULL, NULL),
  ('13.73', '13', 'KOTA', 'Kota Sawahlunto', 'Kota Sawahlunto', 'WIB', NULL, NULL),
  ('13.74', '13', 'KOTA', 'Kota Padang Panjang', 'Kota Padang Panjang', 'WIB', NULL, NULL),
  ('13.75', '13', 'KOTA', 'Kota Bukittinggi', 'Kota Bukittinggi', 'WIB', NULL, NULL),
  ('13.76', '13', 'KOTA', 'Kota Payakumbuh', 'Kota Payakumbuh', 'WIB', NULL, NULL),
  ('13.77', '13', 'KOTA', 'Kota Pariaman', 'Kota Pariaman', 'WIB', NULL, NULL),
  ('14.01', '14', 'KABUPATEN', 'Kabupaten Kampar', NULL, 'WIB', NULL, NULL),
  ('14.02', '14', 'KABUPATEN', 'Kabupaten Indragiri Hulu', NULL, 'WIB', NULL, NULL),
  ('14.03', '14', 'KABUPATEN', 'Kabupaten Bengkalis', NULL, 'WIB', NULL, NULL),
  ('14.04', '14', 'KABUPATEN', 'Kabupaten Indragiri Hilir', NULL, 'WIB', NULL, NULL),
  ('14.05', '14', 'KABUPATEN', 'Kabupaten Pelalawan', NULL, 'WIB', NULL, NULL),
  ('14.06', '14', 'KABUPATEN', 'Kabupaten Rokan Hulu', NULL, 'WIB', NULL, NULL),
  ('14.07', '14', 'KABUPATEN', 'Kabupaten Rokan Hilir', NULL, 'WIB', NULL, NULL),
  ('14.08', '14', 'KABUPATEN', 'Kabupaten Siak', NULL, 'WIB', NULL, NULL),
  ('14.09', '14', 'KABUPATEN', 'Kabupaten Kuantan Singingi', NULL, 'WIB', NULL, NULL),
  ('14.10', '14', 'KABUPATEN', 'Kabupaten Kepulauan Meranti', NULL, 'WIB', NULL, NULL),
  ('14.71', '14', 'KOTA', 'Kota Pekanbaru', 'Kota Pekanbaru', 'WIB', NULL, NULL),
  ('14.72', '14', 'KOTA', 'Kota Dumai', 'Kota Dumai', 'WIB', NULL, NULL),
  ('15.01', '15', 'KABUPATEN', 'Kabupaten Kerinci', NULL, 'WIB', NULL, NULL),
  ('15.02', '15', 'KABUPATEN', 'Kabupaten Merangin', NULL, 'WIB', NULL, NULL),
  ('15.03', '15', 'KABUPATEN', 'Kabupaten Sarolangun', NULL, 'WIB', NULL, NULL),
  ('15.04', '15', 'KABUPATEN', 'Kabupaten Batanghari', NULL, 'WIB', NULL, NULL),
  ('15.05', '15', 'KABUPATEN', 'Kabupaten Muaro Jambi', NULL, 'WIB', NULL, NULL),
  ('15.06', '15', 'KABUPATEN', 'Kabupaten Tanjung Jabung Barat', NULL, 'WIB', NULL, NULL),
  ('15.07', '15', 'KABUPATEN', 'Kabupaten Tanjung Jabung Timur', NULL, 'WIB', NULL, NULL),
  ('15.08', '15', 'KABUPATEN', 'Kabupaten Bungo', NULL, 'WIB', NULL, NULL),
  ('15.09', '15', 'KABUPATEN', 'Kabupaten Tebo', NULL, 'WIB', NULL, NULL),
  ('15.71', '15', 'KOTA', 'Kota Jambi', 'Kota Jambi', 'WIB', NULL, NULL),
  ('15.72', '15', 'KOTA', 'Kota Sungai Penuh', 'Kota Sungai Penuh', 'WIB', NULL, NULL),
  ('16.01', '16', 'KABUPATEN', 'Kabupaten Ogan Komering Ulu', NULL, 'WIB', NULL, NULL),
  ('16.02', '16', 'KABUPATEN', 'Kabupaten Ogan Komering Ilir', NULL, 'WIB', NULL, NULL),
  ('16.03', '16', 'KABUPATEN', 'Kabupaten Muara Enim', NULL, 'WIB', NULL, NULL),
  ('16.04', '16', 'KABUPATEN', 'Kabupaten Lahat', NULL, 'WIB', NULL, NULL),
  ('16.05', '16', 'KABUPATEN', 'Kabupaten Musi Rawas', NULL, 'WIB', NULL, NULL),
  ('16.06', '16', 'KABUPATEN', 'Kabupaten Musi Banyuasin', NULL, 'WIB', NULL, NULL),
  ('16.07', '16', 'KABUPATEN', 'Kabupaten Banyuasin', NULL, 'WIB', NULL, NULL),
  ('16.08', '16', 'KABUPATEN', 'Kabupaten Ogan Komering Ulu Timur', NULL, 'WIB', NULL, NULL),
  ('16.09', '16', 'KABUPATEN', 'Kabupaten Ogan Komering Ulu Selatan', NULL, 'WIB', NULL, NULL),
  ('16.10', '16', 'KABUPATEN', 'Kabupaten Ogan Ilir', NULL, 'WIB', NULL, NULL),
  ('16.11', '16', 'KABUPATEN', 'Kabupaten Empat Lawang', NULL, 'WIB', NULL, NULL),
  ('16.12', '16', 'KABUPATEN', 'Kabupaten Penukal Abab Lematang Ilir', NULL, 'WIB', NULL, NULL),
  ('16.13', '16', 'KABUPATEN', 'Kabupaten Musi Rawas Utara', NULL, 'WIB', NULL, NULL),
  ('16.71', '16', 'KOTA', 'Kota Palembang', 'Kota Palembang', 'WIB', NULL, NULL),
  ('16.72', '16', 'KOTA', 'Kota Pagar Alam', 'Kota Pagar Alam', 'WIB', NULL, NULL),
  ('16.73', '16', 'KOTA', 'Kota Lubuk Linggau', 'Kota Lubuk Linggau', 'WIB', NULL, NULL),
  ('16.74', '16', 'KOTA', 'Kota Prabumulih', 'Kota Prabumulih', 'WIB', NULL, NULL),
  ('17.01', '17', 'KABUPATEN', 'Kabupaten Bengkulu Selatan', NULL, 'WIB', NULL, NULL),
  ('17.02', '17', 'KABUPATEN', 'Kabupaten Rejang Lebong', NULL, 'WIB', NULL, NULL),
  ('17.03', '17', 'KABUPATEN', 'Kabupaten Bengkulu Utara', NULL, 'WIB', NULL, NULL),
  ('17.04', '17', 'KABUPATEN', 'Kabupaten Kaur', NULL, 'WIB', NULL, NULL),
  ('17.05', '17', 'KABUPATEN', 'Kabupaten Seluma', NULL, 'WIB', NULL, NULL),
  ('17.06', '17', 'KABUPATEN', 'Kabupaten Mukomuko', NULL, 'WIB', NULL, NULL),
  ('17.07', '17', 'KABUPATEN', 'Kabupaten Lebong', NULL, 'WIB', NULL, NULL),
  ('17.08', '17', 'KABUPATEN', 'Kabupaten Kepahiang', NULL, 'WIB', NULL, NULL),
  ('17.09', '17', 'KABUPATEN', 'Kabupaten Bengkulu Tengah', NULL, 'WIB', NULL, NULL),
  ('17.71', '17', 'KOTA', 'Kota Bengkulu', 'Kota Bengkulu', 'WIB', NULL, NULL),
  ('18.01', '18', 'KABUPATEN', 'Kabupaten Lampung Selatan', NULL, 'WIB', NULL, NULL),
  ('18.02', '18', 'KABUPATEN', 'Kabupaten Lampung Tengah', NULL, 'WIB', NULL, NULL),
  ('18.03', '18', 'KABUPATEN', 'Kabupaten Lampung Utara', NULL, 'WIB', NULL, NULL),
  ('18.04', '18', 'KABUPATEN', 'Kabupaten Lampung Barat', NULL, 'WIB', NULL, NULL),
  ('18.05', '18', 'KABUPATEN', 'Kabupaten Tulang Bawang', NULL, 'WIB', NULL, NULL),
  ('18.06', '18', 'KABUPATEN', 'Kabupaten Tanggamus', NULL, 'WIB', NULL, NULL),
  ('18.07', '18', 'KABUPATEN', 'Kabupaten Lampung Timur', NULL, 'WIB', NULL, NULL),
  ('18.08', '18', 'KABUPATEN', 'Kabupaten Way Kanan', NULL, 'WIB', NULL, NULL),
  ('18.09', '18', 'KABUPATEN', 'Kabupaten Pesawaran', NULL, 'WIB', NULL, NULL),
  ('18.10', '18', 'KABUPATEN', 'Kabupaten Pringsewu', NULL, 'WIB', NULL, NULL),
  ('18.11', '18', 'KABUPATEN', 'Kabupaten Mesuji', NULL, 'WIB', NULL, NULL),
  ('18.12', '18', 'KABUPATEN', 'Kabupaten Tulang Bawang Barat', NULL, 'WIB', NULL, NULL),
  ('18.13', '18', 'KABUPATEN', 'Kabupaten Pesisir Barat', NULL, 'WIB', NULL, NULL),
  ('18.71', '18', 'KOTA', 'Kota Bandar Lampung', 'Kota Bandar Lampung', 'WIB', NULL, NULL),
  ('18.72', '18', 'KOTA', 'Kota Metro', 'Kota Metro', 'WIB', NULL, NULL),
  ('19.01', '19', 'KABUPATEN', 'Kabupaten Bangka', NULL, 'WIB', NULL, NULL),
  ('19.02', '19', 'KABUPATEN', 'Kabupaten Belitung', NULL, 'WIB', NULL, NULL),
  ('19.03', '19', 'KABUPATEN', 'Kabupaten Bangka Selatan', NULL, 'WIB', NULL, NULL),
  ('19.04', '19', 'KABUPATEN', 'Kabupaten Bangka Tengah', NULL, 'WIB', NULL, NULL),
  ('19.05', '19', 'KABUPATEN', 'Kabupaten Bangka Barat', NULL, 'WIB', NULL, NULL),
  ('19.06', '19', 'KABUPATEN', 'Kabupaten Belitung Timur', NULL, 'WIB', NULL, NULL),
  ('19.71', '19', 'KOTA', 'Kota Pangkal Pinang', 'Kota Pangkal Pinang', 'WIB', NULL, NULL),
  ('21.01', '21', 'KABUPATEN', 'Kabupaten Bintan', NULL, 'WIB', NULL, NULL),
  ('21.02', '21', 'KABUPATEN', 'Kabupaten Karimun', NULL, 'WIB', NULL, NULL),
  ('21.03', '21', 'KABUPATEN', 'Kabupaten Natuna', NULL, 'WIB', NULL, NULL),
  ('21.04', '21', 'KABUPATEN', 'Kabupaten Lingga', NULL, 'WIB', NULL, NULL),
  ('21.05', '21', 'KABUPATEN', 'Kabupaten Kepulauan Anambas', NULL, 'WIB', NULL, NULL),
  ('21.71', '21', 'KOTA', 'Kota Batam', 'Kota Batam', 'WIB', NULL, NULL),
  ('21.72', '21', 'KOTA', 'Kota Tanjung Pinang', 'Kota Tanjung Pinang', 'WIB', NULL, NULL),
  ('31.01', '31', 'KABUPATEN', 'Kabupaten Administrasi Kepulauan Seribu', NULL, 'WIB', NULL, NULL),
  ('31.71', '31', 'KOTA', 'Kota Administrasi Jakarta Pusat', 'Kota Administrasi Jakarta Pusat', 'WIB', NULL, NULL),
  ('31.72', '31', 'KOTA', 'Kota Administrasi Jakarta Utara', 'Kota Administrasi Jakarta Utara', 'WIB', NULL, NULL),
  ('31.73', '31', 'KOTA', 'Kota Administrasi Jakarta Barat', 'Kota Administrasi Jakarta Barat', 'WIB', NULL, NULL),
  ('31.74', '31', 'KOTA', 'Kota Administrasi Jakarta Selatan', 'Kota Administrasi Jakarta Selatan', 'WIB', NULL, NULL),
  ('31.75', '31', 'KOTA', 'Kota Administrasi Jakarta Timur', 'Kota Administrasi Jakarta Timur', 'WIB', NULL, NULL),
  ('32.01', '32', 'KABUPATEN', 'Kabupaten Bogor', 'Cibinong', 'WIB', NULL, NULL),
  ('32.02', '32', 'KABUPATEN', 'Kabupaten Sukabumi', 'Palabuhanratu', 'WIB', NULL, NULL),
  ('32.03', '32', 'KABUPATEN', 'Kabupaten Cianjur', 'Cianjur', 'WIB', NULL, NULL),
  ('32.04', '32', 'KABUPATEN', 'Kabupaten Bandung', 'Soreang', 'WIB', NULL, NULL),
  ('32.05', '32', 'KABUPATEN', 'Kabupaten Garut', 'Tarogong Kidul', 'WIB', NULL, NULL),
  ('32.06', '32', 'KABUPATEN', 'Kabupaten Tasikmalaya', 'Singaparna', 'WIB', NULL, NULL),
  ('32.07', '32', 'KABUPATEN', 'Kabupaten Ciamis', 'Ciamis', 'WIB', NULL, NULL),
  ('32.08', '32', 'KABUPATEN', 'Kabupaten Kuningan', 'Kuningan', 'WIB', NULL, NULL),
  ('32.09', '32', 'KABUPATEN', 'Kabupaten Cirebon', 'Sumber', 'WIB', NULL, NULL),
  ('32.10', '32', 'KABUPATEN', 'Kabupaten Majalengka', 'Majalengka', 'WIB', NULL, NULL),
  ('32.11', '32', 'KABUPATEN', 'Kabupaten Sumedang', 'Sumedang', 'WIB', NULL, NULL),
  ('32.12', '32', 'KABUPATEN', 'Kabupaten Indramayu', 'Indramayu', 'WIB', NULL, NULL),
  ('32.13', '32', 'KABUPATEN', 'Kabupaten Subang', 'Subang', 'WIB', NULL, NULL),
  ('32.14', '32', 'KABUPATEN', 'Kabupaten Purwakarta', 'Purwakarta', 'WIB', NULL, NULL),
  ('32.15', '32', 'KABUPATEN', 'Kabupaten Karawang', 'Karawang', 'WIB', NULL, NULL),
  ('32.16', '32', 'KABUPATEN', 'Kabupaten Bekasi', 'Cikarang Pusat', 'WIB', NULL, NULL),
  ('32.17', '32', 'KABUPATEN', 'Kabupaten Bandung Barat', 'Ngamprah', 'WIB', NULL, NULL),
  ('32.18', '32', 'KABUPATEN', 'Kabupaten Pangandaran', 'Parigi', 'WIB', NULL, NULL),
  ('32.71', '32', 'KOTA', 'Kota Bogor', 'Kota Bogor', 'WIB', NULL, NULL),
  ('32.72', '32', 'KOTA', 'Kota Sukabumi', 'Kota Sukabumi', 'WIB', NULL, NULL),
  ('32.73', '32', 'KOTA', 'Kota Bandung', 'Kota Bandung', 'WIB', NULL, NULL),
  ('32.74', '32', 'KOTA', 'Kota Cirebon', 'Kota Cirebon', 'WIB', NULL, NULL),
  ('32.75', '32', 'KOTA', 'Kota Bekasi', 'Kota Bekasi', 'WIB', NULL, NULL),
  ('32.76', '32', 'KOTA', 'Kota Depok', 'Kota Depok', 'WIB', NULL, NULL),
  ('32.77', '32', 'KOTA', 'Kota Cimahi', 'Kota Cimahi', 'WIB', NULL, NULL),
  ('32.78', '32', 'KOTA', 'Kota Tasikmalaya', 'Kota Tasikmalaya', 'WIB', NULL, NULL),
  ('32.79', '32', 'KOTA', 'Kota Banjar', 'Kota Banjar', 'WIB', NULL, NULL),
  ('33.01', '33', 'KABUPATEN', 'Kabupaten Cilacap', NULL, 'WIB', NULL, NULL),
  ('33.02', '33', 'KABUPATEN', 'Kabupaten Banyumas', 'Purwokerto', 'WIB', NULL, NULL),
  ('33.03', '33', 'KABUPATEN', 'Kabupaten Purbalingga', NULL, 'WIB', NULL, NULL),
  ('33.04', '33', 'KABUPATEN', 'Kabupaten Banjarnegara', 'Banjarnegara', 'WIB', NULL, NULL),
  ('33.05', '33', 'KABUPATEN', 'Kabupaten Kebumen', 'Kebumen', 'WIB', NULL, NULL),
  ('33.06', '33', 'KABUPATEN', 'Kabupaten Purworejo', 'Purworejo', 'WIB', NULL, NULL),
  ('33.07', '33', 'KABUPATEN', 'Kabupaten Wonosobo', 'Wonosobo', 'WIB', NULL, NULL),
  ('33.08', '33', 'KABUPATEN', 'Kabupaten Magelang', 'Mungkid', 'WIB', NULL, NULL),
  ('33.09', '33', 'KABUPATEN', 'Kabupaten Boyolali', 'Boyolali', 'WIB', NULL, NULL),
  ('33.10', '33', 'KABUPATEN', 'Kabupaten Klaten', 'Klaten', 'WIB', NULL, NULL),
  ('33.11', '33', 'KABUPATEN', 'Kabupaten Sukoharjo', 'Sukoharjo', 'WIB', NULL, NULL),
  ('33.12', '33', 'KABUPATEN', 'Kabupaten Wonogiri', 'Wonogiri', 'WIB', NULL, NULL),
  ('33.13', '33', 'KABUPATEN', 'Kabupaten Karanganyar', 'Karanganyar', 'WIB', NULL, NULL),
  ('33.14', '33', 'KABUPATEN', 'Kabupaten Sragen', 'Sragen', 'WIB', NULL, NULL),
  ('33.15', '33', 'KABUPATEN', 'Kabupaten Grobogan', 'Purwodadi', 'WIB', NULL, NULL),
  ('33.16', '33', 'KABUPATEN', 'Kabupaten Blora', 'Blora', 'WIB', NULL, NULL),
  ('33.17', '33', 'KABUPATEN', 'Kabupaten Rembang', 'Rembang', 'WIB', NULL, NULL),
  ('33.18', '33', 'KABUPATEN', 'Kabupaten Pati', 'Pati', 'WIB', NULL, NULL),
  ('33.19', '33', 'KABUPATEN', 'Kabupaten Kudus', 'Kudus', 'WIB', NULL, NULL),
  ('33.20', '33', 'KABUPATEN', 'Kabupaten Jepara', 'Jepara', 'WIB', NULL, NULL),
  ('33.21', '33', 'KABUPATEN', 'Kabupaten Demak', 'Demak', 'WIB', NULL, NULL),
  ('33.22', '33', 'KABUPATEN', 'Kabupaten Semarang', 'Ungaran', 'WIB', NULL, NULL),
  ('33.23', '33', 'KABUPATEN', 'Kabupaten Temanggung', 'Temanggung', 'WIB', NULL, NULL),
  ('33.24', '33', 'KABUPATEN', 'Kabupaten Kendal', 'Kendal', 'WIB', NULL, NULL),
  ('33.25', '33', 'KABUPATEN', 'Kabupaten Batang', 'Batang', 'WIB', NULL, NULL),
  ('33.26', '33', 'KABUPATEN', 'Kabupaten Pekalongan', 'Kajen', 'WIB', NULL, NULL),
  ('33.27', '33', 'KABUPATEN', 'Kabupaten Pemalang', 'Pemalang', 'WIB', NULL, NULL),
  ('33.28', '33', 'KABUPATEN', 'Kabupaten Tegal', 'Slawi', 'WIB', NULL, NULL),
  ('33.29', '33', 'KABUPATEN', 'Kabupaten Brebes', 'Brebes', 'WIB', NULL, NULL),
  ('33.71', '33', 'KOTA', 'Kota Magelang', 'Kota Magelang', 'WIB', NULL, NULL),
  ('33.72', '33', 'KOTA', 'Kota Surakarta', 'Kota Surakarta', 'WIB', NULL, NULL),
  ('33.73', '33', 'KOTA', 'Kota Salatiga', 'Kota Salatiga', 'WIB', NULL, NULL),
  ('33.74', '33', 'KOTA', 'Kota Semarang', 'Kota Semarang', 'WIB', NULL, NULL),
  ('33.75', '33', 'KOTA', 'Kota Pekalongan', 'Kota Pekalongan', 'WIB', NULL, NULL),
  ('33.76', '33', 'KOTA', 'Kota Tegal', 'Kota Tegal', 'WIB', NULL, NULL),
  ('34.01', '34', 'KABUPATEN', 'Kabupaten Kulon Progo', 'Wates', 'WIB', NULL, NULL),
  ('34.02', '34', 'KABUPATEN', 'Kabupaten Bantul', 'Bantul', 'WIB', NULL, NULL),
  ('34.03', '34', 'KABUPATEN', 'Kabupaten Gunungkidul', 'Wonosari', 'WIB', NULL, NULL),
  ('34.04', '34', 'KABUPATEN', 'Kabupaten Sleman', 'Sleman', 'WIB', NULL, NULL),
  ('34.71', '34', 'KOTA', 'Kota Yogyakarta', 'Kota Yogyakarta', 'WIB', NULL, NULL),
  ('35.01', '35', 'KABUPATEN', 'Kabupaten Pacitan', 'Pacitan', 'WIB', NULL, NULL),
  ('35.02', '35', 'KABUPATEN', 'Kabupaten Ponorogo', 'Ponorogo', 'WIB', NULL, NULL),
  ('35.03', '35', 'KABUPATEN', 'Kabupaten Trenggalek', 'Trenggalek', 'WIB', NULL, NULL),
  ('35.04', '35', 'KABUPATEN', 'Kabupaten Tulungagung', 'Tulungagung', 'WIB', NULL, NULL),
  ('35.05', '35', 'KABUPATEN', 'Kabupaten Blitar', 'Kanigoro', 'WIB', NULL, NULL),
  ('35.06', '35', 'KABUPATEN', 'Kabupaten Kediri', 'Ngasem', 'WIB', NULL, NULL),
  ('35.07', '35', 'KABUPATEN', 'Kabupaten Malang', 'Kepanjen', 'WIB', NULL, NULL),
  ('35.08', '35', 'KABUPATEN', 'Kabupaten Lumajang', 'Lumajang', 'WIB', NULL, NULL),
  ('35.09', '35', 'KABUPATEN', 'Kabupaten Jember', 'Jember', 'WIB', NULL, NULL),
  ('35.10', '35', 'KABUPATEN', 'Kabupaten Banyuwangi', 'Banyuwangi', 'WIB', NULL, NULL),
  ('35.11', '35', 'KABUPATEN', 'Kabupaten Bondowoso', 'Bondowoso', 'WIB', NULL, NULL),
  ('35.12', '35', 'KABUPATEN', 'Kabupaten Situbondo', 'Situbondo', 'WIB', NULL, NULL),
  ('35.13', '35', 'KABUPATEN', 'Kabupaten Probolinggo', 'Kraksaan', 'WIB', NULL, NULL),
  ('35.14', '35', 'KABUPATEN', 'Kabupaten Pasuruan', 'Bangil', 'WIB', NULL, NULL),
  ('35.15', '35', 'KABUPATEN', 'Kabupaten Sidoarjo', 'Sidoarjo', 'WIB', NULL, NULL),
  ('35.16', '35', 'KABUPATEN', 'Kabupaten Mojokerto', 'Mojosari', 'WIB', NULL, NULL),
  ('35.17', '35', 'KABUPATEN', 'Kabupaten Jombang', 'Jombang', 'WIB', NULL, NULL),
  ('35.18', '35', 'KABUPATEN', 'Kabupaten Nganjuk', 'Nganjuk', 'WIB', NULL, NULL),
  ('35.19', '35', 'KABUPATEN', 'Kabupaten Madiun', 'Caruban', 'WIB', NULL, NULL),
  ('35.20', '35', 'KABUPATEN', 'Kabupaten Magetan', 'Magetan', 'WIB', NULL, NULL),
  ('35.21', '35', 'KABUPATEN', 'Kabupaten Ngawi', 'Ngawi', 'WIB', NULL, NULL),
  ('35.22', '35', 'KABUPATEN', 'Kabupaten Bojonegoro', 'Bojonegoro', 'WIB', NULL, NULL),
  ('35.23', '35', 'KABUPATEN', 'Kabupaten Tuban', 'Tuban', 'WIB', NULL, NULL),
  ('35.24', '35', 'KABUPATEN', 'Kabupaten Lamongan', 'Lamongan', 'WIB', NULL, NULL),
  ('35.25', '35', 'KABUPATEN', 'Kabupaten Gresik', 'Gresik', 'WIB', NULL, NULL),
  ('35.26', '35', 'KABUPATEN', 'Kabupaten Bangkalan', 'Bangkalan', 'WIB', NULL, NULL),
  ('35.27', '35', 'KABUPATEN', 'Kabupaten Sampang', 'Sampang', 'WIB', NULL, NULL),
  ('35.28', '35', 'KABUPATEN', 'Kabupaten Pamekasan', 'Pamekasan', 'WIB', NULL, NULL),
  ('35.29', '35', 'KABUPATEN', 'Kabupaten Sumenep', 'Sumenep', 'WIB', NULL, NULL),
  ('35.71', '35', 'KOTA', 'Kota Kediri', 'Kota Kediri', 'WIB', NULL, NULL),
  ('35.72', '35', 'KOTA', 'Kota Blitar', 'Kota Blitar', 'WIB', NULL, NULL),
  ('35.73', '35', 'KOTA', 'Kota Malang', 'Kota Malang', 'WIB', NULL, NULL),
  ('35.74', '35', 'KOTA', 'Kota Probolinggo', 'Kota Probolinggo', 'WIB', NULL, NULL),
  ('35.75', '35', 'KOTA', 'Kota Pasuruan', 'Kota Pasuruan', 'WIB', NULL, NULL),
  ('35.76', '35', 'KOTA', 'Kota Mojokerto', 'Kota Mojokerto', 'WIB', NULL, NULL),
  ('35.77', '35', 'KOTA', 'Kota Madiun', 'Kota Madiun', 'WIB', NULL, NULL),
  ('35.78', '35', 'KOTA', 'Kota Surabaya', 'Kota Surabaya', 'WIB', NULL, NULL),
  ('35.79', '35', 'KOTA', 'Kota Batu', 'Kota Batu', 'WIB', NULL, NULL),
  ('36.01', '36', 'KABUPATEN', 'Kabupaten Pandeglang', NULL, 'WIB', NULL, NULL),
  ('36.02', '36', 'KABUPATEN', 'Kabupaten Lebak', NULL, 'WIB', NULL, NULL),
  ('36.03', '36', 'KABUPATEN', 'Kabupaten Tangerang', NULL, 'WIB', NULL, NULL),
  ('36.04', '36', 'KABUPATEN', 'Kabupaten Serang', NULL, 'WIB', NULL, NULL),
  ('36.71', '36', 'KOTA', 'Kota Tangerang', 'Kota Tangerang', 'WIB', NULL, NULL),
  ('36.72', '36', 'KOTA', 'Kota Cilegon', 'Kota Cilegon', 'WIB', NULL, NULL),
  ('36.73', '36', 'KOTA', 'Kota Serang', 'Kota Serang', 'WIB', NULL, NULL),
  ('36.74', '36', 'KOTA', 'Kota Tangerang Selatan', 'Kota Tangerang Selatan', 'WIB', NULL, NULL),
  ('51.01', '51', 'KABUPATEN', 'Kabupaten Jembrana', 'Negara', 'WITA', NULL, NULL),
  ('51.02', '51', 'KABUPATEN', 'Kabupaten Tabanan', 'Tabanan', 'WITA', NULL, NULL),
  ('51.03', '51', 'KABUPATEN', 'Kabupaten Badung', 'Mangupura', 'WITA', NULL, NULL),
  ('51.04', '51', 'KABUPATEN', 'Kabupaten Gianyar', 'Gianyar', 'WITA', NULL, NULL),
  ('51.05', '51', 'KABUPATEN', 'Kabupaten Klungkung', 'Semarapura', 'WITA', NULL, NULL),
  ('51.06', '51', 'KABUPATEN', 'Kabupaten Bangli', 'Bangli', 'WITA', NULL, NULL),
  ('51.07', '51', 'KABUPATEN', 'Kabupaten Karangasem', 'Amlapura', 'WITA', NULL, NULL),
  ('51.08', '51', 'KABUPATEN', 'Kabupaten Buleleng', 'Singaraja', 'WITA', NULL, NULL),
  ('51.71', '51', 'KOTA', 'Kota Denpasar', 'Kota Denpasar', 'WITA', NULL, NULL),
  ('52.01', '52', 'KABUPATEN', 'Kabupaten Lombok Barat', NULL, 'WITA', NULL, NULL),
  ('52.02', '52', 'KABUPATEN', 'Kabupaten Lombok Tengah', NULL, 'WITA', NULL, NULL),
  ('52.03', '52', 'KABUPATEN', 'Kabupaten Lombok Timur', NULL, 'WITA', NULL, NULL),
  ('52.04', '52', 'KABUPATEN', 'Kabupaten Sumbawa', NULL, 'WITA', NULL, NULL),
  ('52.05', '52', 'KABUPATEN', 'Kabupaten Dompu', NULL, 'WITA', NULL, NULL),
  ('52.06', '52', 'KABUPATEN', 'Kabupaten Bima', NULL, 'WITA', NULL, NULL),
  ('52.07', '52', 'KABUPATEN', 'Kabupaten Sumbawa Barat', NULL, 'WITA', NULL, NULL),
  ('52.08', '52', 'KABUPATEN', 'Kabupaten Lombok Utara', NULL, 'WITA', NULL, NULL),
  ('52.71', '52', 'KOTA', 'Kota Mataram', 'Kota Mataram', 'WITA', NULL, NULL),
  ('52.72', '52', 'KOTA', 'Kota Bima', 'Kota Bima', 'WITA', NULL, NULL),
  ('53.01', '53', 'KABUPATEN', 'Kabupaten Kupang', NULL, 'WITA', NULL, NULL),
  ('53.02', '53', 'KABUPATEN', 'Kabupaten Timor Tengah Selatan', NULL, 'WITA', NULL, NULL),
  ('53.03', '53', 'KABUPATEN', 'Kabupaten Timor Tengah Utara', NULL, 'WITA', NULL, NULL),
  ('53.04', '53', 'KABUPATEN', 'Kabupaten Belu', NULL, 'WITA', NULL, NULL),
  ('53.05', '53', 'KABUPATEN', 'Kabupaten Alor', NULL, 'WITA', NULL, NULL),
  ('53.06', '53', 'KABUPATEN', 'Kabupaten Flores Timur', NULL, 'WITA', NULL, NULL),
  ('53.07', '53', 'KABUPATEN', 'Kabupaten Sikka', NULL, 'WITA', NULL, NULL),
  ('53.08', '53', 'KABUPATEN', 'Kabupaten Ende', NULL, 'WITA', NULL, NULL),
  ('53.09', '53', 'KABUPATEN', 'Kabupaten Ngada', NULL, 'WITA', NULL, NULL),
  ('53.10', '53', 'KABUPATEN', 'Kabupaten Manggarai', NULL, 'WITA', NULL, NULL),
  ('53.11', '53', 'KABUPATEN', 'Kabupaten Sumba Timur', NULL, 'WITA', NULL, NULL),
  ('53.12', '53', 'KABUPATEN', 'Kabupaten Sumba Barat', NULL, 'WITA', NULL, NULL),
  ('53.13', '53', 'KABUPATEN', 'Kabupaten Lembata', NULL, 'WITA', NULL, NULL),
  ('53.14', '53', 'KABUPATEN', 'Kabupaten Rote Ndao', NULL, 'WITA', NULL, NULL),
  ('53.15', '53', 'KABUPATEN', 'Kabupaten Manggarai Barat', NULL, 'WITA', NULL, NULL),
  ('53.16', '53', 'KABUPATEN', 'Kabupaten Nagekeo', NULL, 'WITA', NULL, NULL),
  ('53.17', '53', 'KABUPATEN', 'Kabupaten Sumba Tengah', NULL, 'WITA', NULL, NULL),
  ('53.18', '53', 'KABUPATEN', 'Kabupaten Sumba Barat Daya', NULL, 'WITA', NULL, NULL),
  ('53.19', '53', 'KABUPATEN', 'Kabupaten Manggarai Timur', NULL, 'WITA', NULL, NULL),
  ('53.20', '53', 'KABUPATEN', 'Kabupaten Sabu Raijua', NULL, 'WITA', NULL, NULL),
  ('53.21', '53', 'KABUPATEN', 'Kabupaten Malaka', NULL, 'WITA', NULL, NULL),
  ('53.71', '53', 'KOTA', 'Kota Kupang', 'Kota Kupang', 'WITA', NULL, NULL),
  ('61.01', '61', 'KABUPATEN', 'Kabupaten Sambas', NULL, 'WIB', NULL, NULL),
  ('61.02', '61', 'KABUPATEN', 'Kabupaten Mempawah', NULL, 'WIB', NULL, NULL),
  ('61.03', '61', 'KABUPATEN', 'Kabupaten Sanggau', NULL, 'WIB', NULL, NULL),
  ('61.04', '61', 'KABUPATEN', 'Kabupaten Ketapang', NULL, 'WIB', NULL, NULL),
  ('61.05', '61', 'KABUPATEN', 'Kabupaten Sintang', NULL, 'WIB', NULL, NULL),
  ('61.06', '61', 'KABUPATEN', 'Kabupaten Kapuas Hulu', NULL, 'WIB', NULL, NULL),
  ('61.07', '61', 'KABUPATEN', 'Kabupaten Bengkayang', NULL, 'WIB', NULL, NULL),
  ('61.08', '61', 'KABUPATEN', 'Kabupaten Landak', NULL, 'WIB', NULL, NULL),
  ('61.09', '61', 'KABUPATEN', 'Kabupaten Sekadau', NULL, 'WIB', NULL, NULL),
  ('61.10', '61', 'KABUPATEN', 'Kabupaten Melawi', NULL, 'WIB', NULL, NULL),
  ('61.11', '61', 'KABUPATEN', 'Kabupaten Kayong Utara', NULL, 'WIB', NULL, NULL),
  ('61.12', '61', 'KABUPATEN', 'Kabupaten Kubu Raya', NULL, 'WIB', NULL, NULL),
  ('61.71', '61', 'KOTA', 'Kota Pontianak', 'Kota Pontianak', 'WIB', NULL, NULL),
  ('61.72', '61', 'KOTA', 'Kota Singkawang', 'Kota Singkawang', 'WIB', NULL, NULL),
  ('62.01', '62', 'KABUPATEN', 'Kabupaten Kotawaringin Barat', NULL, 'WIB', NULL, NULL),
  ('62.02', '62', 'KABUPATEN', 'Kabupaten Kotawaringin Timur', NULL, 'WIB', NULL, NULL),
  ('62.03', '62', 'KABUPATEN', 'Kabupaten Kapuas', NULL, 'WIB', NULL, NULL),
  ('62.04', '62', 'KABUPATEN', 'Kabupaten Barito Selatan', NULL, 'WIB', NULL, NULL),
  ('62.05', '62', 'KABUPATEN', 'Kabupaten Barito Utara', NULL, 'WIB', NULL, NULL),
  ('62.06', '62', 'KABUPATEN', 'Kabupaten Katingan', NULL, 'WIB', NULL, NULL),
  ('62.07', '62', 'KABUPATEN', 'Kabupaten Seruyan', NULL, 'WIB', NULL, NULL),
  ('62.08', '62', 'KABUPATEN', 'Kabupaten Sukamara', NULL, 'WIB', NULL, NULL),
  ('62.09', '62', 'KABUPATEN', 'Kabupaten Lamandau', NULL, 'WIB', NULL, NULL),
  ('62.10', '62', 'KABUPATEN', 'Kabupaten Gunung Mas', NULL, 'WIB', NULL, NULL),
  ('62.11', '62', 'KABUPATEN', 'Kabupaten Pulang Pisau', NULL, 'WIB', NULL, NULL),
  ('62.12', '62', 'KABUPATEN', 'Kabupaten Murung Raya', NULL, 'WIB', NULL, NULL),
  ('62.13', '62', 'KABUPATEN', 'Kabupaten Barito Timur', NULL, 'WIB', NULL, NULL),
  ('62.71', '62', 'KOTA', 'Kota Palangkaraya', 'Kota Palangkaraya', 'WIB', NULL, NULL),
  ('63.01', '63', 'KABUPATEN', 'Kabupaten Tanah Laut', NULL, 'WITA', NULL, NULL),
  ('63.02', '63', 'KABUPATEN', 'Kabupaten Kotabaru', NULL, 'WITA', NULL, NULL),
  ('63.03', '63', 'KABUPATEN', 'Kabupaten Banjar', NULL, 'WITA', NULL, NULL),
  ('63.04', '63', 'KABUPATEN', 'Kabupaten Barito Kuala', NULL, 'WITA', NULL, NULL),
  ('63.05', '63', 'KABUPATEN', 'Kabupaten Tapin', NULL, 'WITA', NULL, NULL),
  ('63.06', '63', 'KABUPATEN', 'Kabupaten Hulu Sungai Selatan', NULL, 'WITA', NULL, NULL),
  ('63.07', '63', 'KABUPATEN', 'Kabupaten Hulu Sungai Tengah', NULL, 'WITA', NULL, NULL),
  ('63.08', '63', 'KABUPATEN', 'Kabupaten Hulu Sungai Utara', NULL, 'WITA', NULL, NULL),
  ('63.09', '63', 'KABUPATEN', 'Kabupaten Tabalong', NULL, 'WITA', NULL, NULL),
  ('63.10', '63', 'KABUPATEN', 'Kabupaten Tanah Bumbu', NULL, 'WITA', NULL, NULL),
  ('63.11', '63', 'KABUPATEN', 'Kabupaten Balangan', NULL, 'WITA', NULL, NULL),
  ('63.71', '63', 'KOTA', 'Kota Banjarmasin', 'Kota Banjarmasin', 'WITA', NULL, NULL),
  ('63.72', '63', 'KOTA', 'Kota Banjarbaru', 'Kota Banjarbaru', 'WITA', NULL, NULL),
  ('64.01', '64', 'KABUPATEN', 'Kabupaten Paser', NULL, 'WITA', NULL, NULL),
  ('64.02', '64', 'KABUPATEN', 'Kabupaten Kutai Kartanegara', NULL, 'WITA', NULL, NULL),
  ('64.03', '64', 'KABUPATEN', 'Kabupaten Berau', NULL, 'WITA', NULL, NULL),
  ('64.07', '64', 'KABUPATEN', 'Kabupaten Kutai Barat', NULL, 'WITA', NULL, NULL),
  ('64.08', '64', 'KABUPATEN', 'Kabupaten Kutai Timur', NULL, 'WITA', NULL, NULL),
  ('64.09', '64', 'KABUPATEN', 'Kabupaten Penajam Paser Utara', NULL, 'WITA', NULL, NULL),
  ('64.11', '64', 'KABUPATEN', 'Kabupaten Mahakam Ulu', NULL, 'WITA', NULL, NULL),
  ('64.71', '64', 'KOTA', 'Kota Balikpapan', 'Kota Balikpapan', 'WITA', NULL, NULL),
  ('64.72', '64', 'KOTA', 'Kota Samarinda', 'Kota Samarinda', 'WITA', NULL, NULL),
  ('64.74', '64', 'KOTA', 'Kota Bontang', 'Kota Bontang', 'WITA', NULL, NULL),
  ('65.01', '65', 'KABUPATEN', 'Kabupaten Bulungan', NULL, 'WITA', NULL, NULL),
  ('65.02', '65', 'KABUPATEN', 'Kabupaten Malinau', NULL, 'WITA', NULL, NULL),
  ('65.03', '65', 'KABUPATEN', 'Kabupaten Nunukan', NULL, 'WITA', NULL, NULL),
  ('65.04', '65', 'KABUPATEN', 'Kabupaten Tana Tidung', NULL, 'WITA', NULL, NULL),
  ('65.71', '65', 'KOTA', 'Kota Tarakan', 'Kota Tarakan', 'WITA', NULL, NULL),
  ('71.01', '71', 'KABUPATEN', 'Kabupaten Bolaang Mongondow', NULL, 'WITA', NULL, NULL),
  ('71.02', '71', 'KABUPATEN', 'Kabupaten Minahasa', NULL, 'WITA', NULL, NULL),
  ('71.03', '71', 'KABUPATEN', 'Kabupaten Kepulauan Sangihe', NULL, 'WITA', NULL, NULL),
  ('71.04', '71', 'KABUPATEN', 'Kabupaten Kepulauan Talaud', NULL, 'WITA', NULL, NULL),
  ('71.05', '71', 'KABUPATEN', 'Kabupaten Minahasa Selatan', NULL, 'WITA', NULL, NULL),
  ('71.06', '71', 'KABUPATEN', 'Kabupaten Minahasa Utara', NULL, 'WITA', NULL, NULL),
  ('71.07', '71', 'KABUPATEN', 'Kabupaten Minahasa Tenggara', NULL, 'WITA', NULL, NULL),
  ('71.08', '71', 'KABUPATEN', 'Kabupaten Bolaang Mongondow Utara', NULL, 'WITA', NULL, NULL),
  ('71.09', '71', 'KABUPATEN', 'Kabupaten Kep. Siau Tagulandang Biaro', NULL, 'WITA', NULL, NULL),
  ('71.10', '71', 'KABUPATEN', 'Kabupaten Bolaang Mongondow Timur', NULL, 'WITA', NULL, NULL),
  ('71.11', '71', 'KABUPATEN', 'Kabupaten Bolaang Mongondow Selatan', NULL, 'WITA', NULL, NULL),
  ('71.71', '71', 'KOTA', 'Kota Manado', 'Kota Manado', 'WITA', NULL, NULL),
  ('71.72', '71', 'KOTA', 'Kota Bitung', 'Kota Bitung', 'WITA', NULL, NULL),
  ('71.73', '71', 'KOTA', 'Kota Tomohon', 'Kota Tomohon', 'WITA', NULL, NULL),
  ('71.74', '71', 'KOTA', 'Kota Kotamobagu', 'Kota Kotamobagu', 'WITA', NULL, NULL),
  ('72.01', '72', 'KABUPATEN', 'Kabupaten Banggai', NULL, 'WITA', NULL, NULL),
  ('72.02', '72', 'KABUPATEN', 'Kabupaten Poso', NULL, 'WITA', NULL, NULL),
  ('72.03', '72', 'KABUPATEN', 'Kabupaten Donggala', NULL, 'WITA', NULL, NULL),
  ('72.04', '72', 'KABUPATEN', 'Kabupaten Toli-Toli', NULL, 'WITA', NULL, NULL),
  ('72.05', '72', 'KABUPATEN', 'Kabupaten Buol', NULL, 'WITA', NULL, NULL),
  ('72.06', '72', 'KABUPATEN', 'Kabupaten Morowali', NULL, 'WITA', NULL, NULL),
  ('72.07', '72', 'KABUPATEN', 'Kabupaten Banggai Kepulauan', NULL, 'WITA', NULL, NULL),
  ('72.08', '72', 'KABUPATEN', 'Kabupaten Parigi Moutong', NULL, 'WITA', NULL, NULL),
  ('72.09', '72', 'KABUPATEN', 'Kabupaten Tojo Una Una', NULL, 'WITA', NULL, NULL),
  ('72.10', '72', 'KABUPATEN', 'Kabupaten Sigi', NULL, 'WITA', NULL, NULL),
  ('72.11', '72', 'KABUPATEN', 'Kabupaten Banggai Laut', NULL, 'WITA', NULL, NULL),
  ('72.12', '72', 'KABUPATEN', 'Kabupaten Morowali Utara', NULL, 'WITA', NULL, NULL),
  ('72.71', '72', 'KOTA', 'Kota Palu', 'Kota Palu', 'WITA', NULL, NULL),
  ('73.01', '73', 'KABUPATEN', 'Kabupaten Kepulauan Selayar', NULL, 'WITA', NULL, NULL),
  ('73.02', '73', 'KABUPATEN', 'Kabupaten Bulukumba', NULL, 'WITA', NULL, NULL),
  ('73.03', '73', 'KABUPATEN', 'Kabupaten Bantaeng', NULL, 'WITA', NULL, NULL),
  ('73.04', '73', 'KABUPATEN', 'Kabupaten Jeneponto', NULL, 'WITA', NULL, NULL),
  ('73.05', '73', 'KABUPATEN', 'Kabupaten Takalar', NULL, 'WITA', NULL, NULL),
  ('73.06', '73', 'KABUPATEN', 'Kabupaten Gowa', NULL, 'WITA', NULL, NULL),
  ('73.07', '73', 'KABUPATEN', 'Kabupaten Sinjai', NULL, 'WITA', NULL, NULL),
  ('73.08', '73', 'KABUPATEN', 'Kabupaten Bone', NULL, 'WITA', NULL, NULL),
  ('73.09', '73', 'KABUPATEN', 'Kabupaten Maros', NULL, 'WITA', NULL, NULL),
  ('73.10', '73', 'KABUPATEN', 'Kabupaten Pangkajene dan Kepulauan', NULL, 'WITA', NULL, NULL),
  ('73.11', '73', 'KABUPATEN', 'Kabupaten Barru', NULL, 'WITA', NULL, NULL),
  ('73.12', '73', 'KABUPATEN', 'Kabupaten Soppeng', NULL, 'WITA', NULL, NULL),
  ('73.13', '73', 'KABUPATEN', 'Kabupaten Wajo', NULL, 'WITA', NULL, NULL),
  ('73.14', '73', 'KABUPATEN', 'Kabupaten Sidenreng Rappang', NULL, 'WITA', NULL, NULL),
  ('73.15', '73', 'KABUPATEN', 'Kabupaten Pinrang', NULL, 'WITA', NULL, NULL),
  ('73.16', '73', 'KABUPATEN', 'Kabupaten Enrekang', NULL, 'WITA', NULL, NULL),
  ('73.17', '73', 'KABUPATEN', 'Kabupaten Luwu', NULL, 'WITA', NULL, NULL),
  ('73.18', '73', 'KABUPATEN', 'Kabupaten Tana Toraja', NULL, 'WITA', NULL, NULL),
  ('73.22', '73', 'KABUPATEN', 'Kabupaten Luwu Utara', NULL, 'WITA', NULL, NULL),
  ('73.24', '73', 'KABUPATEN', 'Kabupaten Luwu Timur', NULL, 'WITA', NULL, NULL),
  ('73.26', '73', 'KABUPATEN', 'Kabupaten Toraja Utara', NULL, 'WITA', NULL, NULL),
  ('73.71', '73', 'KOTA', 'Kota Makassar', 'Kota Makassar', 'WITA', NULL, NULL),
  ('73.72', '73', 'KOTA', 'Kota Parepare', 'Kota Parepare', 'WITA', NULL, NULL),
  ('73.73', '73', 'KOTA', 'Kota Palopo', 'Kota Palopo', 'WITA', NULL, NULL),
  ('74.01', '74', 'KABUPATEN', 'Kabupaten Kolaka', NULL, 'WITA', NULL, NULL),
  ('74.02', '74', 'KABUPATEN', 'Kabupaten Konawe', NULL, 'WITA', NULL, NULL),
  ('74.03', '74', 'KABUPATEN', 'Kabupaten Muna', NULL, 'WITA', NULL, NULL),
  ('74.04', '74', 'KABUPATEN', 'Kabupaten Buton', NULL, 'WITA', NULL, NULL),
  ('74.05', '74', 'KABUPATEN', 'Kabupaten Konawe Selatan', NULL, 'WITA', NULL, NULL),
  ('74.06', '74', 'KABUPATEN', 'Kabupaten Bombana', NULL, 'WITA', NULL, NULL),
  ('74.07', '74', 'KABUPATEN', 'Kabupaten Wakatobi', NULL, 'WITA', NULL, NULL),
  ('74.08', '74', 'KABUPATEN', 'Kabupaten Kolaka Utara', NULL, 'WITA', NULL, NULL),
  ('74.09', '74', 'KABUPATEN', 'Kabupaten Konawe Utara', NULL, 'WITA', NULL, NULL),
  ('74.10', '74', 'KABUPATEN', 'Kabupaten Buton Utara', NULL, 'WITA', NULL, NULL),
  ('74.11', '74', 'KABUPATEN', 'Kabupaten Kolaka Timur', NULL, 'WITA', NULL, NULL),
  ('74.12', '74', 'KABUPATEN', 'Kabupaten Konawe Kepulauan', NULL, 'WITA', NULL, NULL),
  ('74.13', '74', 'KABUPATEN', 'Kabupaten Muna Barat', NULL, 'WITA', NULL, NULL),
  ('74.14', '74', 'KABUPATEN', 'Kabupaten Buton Tengah', NULL, 'WITA', NULL, NULL),
  ('74.15', '74', 'KABUPATEN', 'Kabupaten Buton Selatan', NULL, 'WITA', NULL, NULL),
  ('74.71', '74', 'KOTA', 'Kota Kendari', 'Kota Kendari', 'WITA', NULL, NULL),
  ('74.72', '74', 'KOTA', 'Kota Bau Bau', 'Kota Bau Bau', 'WITA', NULL, NULL),
  ('75.01', '75', 'KABUPATEN', 'Kabupaten Gorontalo', NULL, 'WITA', NULL, NULL),
  ('75.02', '75', 'KABUPATEN', 'Kabupaten Boalemo', NULL, 'WITA', NULL, NULL),
  ('75.03', '75', 'KABUPATEN', 'Kabupaten Bone Bolango', NULL, 'WITA', NULL, NULL),
  ('75.04', '75', 'KABUPATEN', 'Kabupaten Pohuwato', NULL, 'WITA', NULL, NULL),
  ('75.05', '75', 'KABUPATEN', 'Kabupaten Gorontalo Utara', NULL, 'WITA', NULL, NULL),
  ('75.71', '75', 'KOTA', 'Kota Gorontalo', 'Kota Gorontalo', 'WITA', NULL, NULL),
  ('76.01', '76', 'KABUPATEN', 'Kabupaten Pasangkayu', NULL, 'WITA', NULL, NULL),
  ('76.02', '76', 'KABUPATEN', 'Kabupaten Mamuju', NULL, 'WITA', NULL, NULL),
  ('76.03', '76', 'KABUPATEN', 'Kabupaten Mamasa', NULL, 'WITA', NULL, NULL),
  ('76.04', '76', 'KABUPATEN', 'Kabupaten Polewali Mandar', NULL, 'WITA', NULL, NULL),
  ('76.05', '76', 'KABUPATEN', 'Kabupaten Majene', NULL, 'WITA', NULL, NULL),
  ('76.06', '76', 'KABUPATEN', 'Kabupaten Mamuju Tengah', NULL, 'WITA', NULL, NULL),
  ('81.01', '81', 'KABUPATEN', 'Kabupaten Maluku Tengah', NULL, 'WIT', NULL, NULL),
  ('81.02', '81', 'KABUPATEN', 'Kabupaten Maluku Tenggara', NULL, 'WIT', NULL, NULL),
  ('81.03', '81', 'KABUPATEN', 'Kabupaten Kepulauan Tanimbar', NULL, 'WIT', NULL, NULL),
  ('81.04', '81', 'KABUPATEN', 'Kabupaten Buru', NULL, 'WIT', NULL, NULL),
  ('81.05', '81', 'KABUPATEN', 'Kabupaten Seram Bagian Timur', NULL, 'WIT', NULL, NULL),
  ('81.06', '81', 'KABUPATEN', 'Kabupaten Seram Bagian Barat', NULL, 'WIT', NULL, NULL),
  ('81.07', '81', 'KABUPATEN', 'Kabupaten Kepulauan Aru', NULL, 'WIT', NULL, NULL),
  ('81.08', '81', 'KABUPATEN', 'Kabupaten Maluku Barat Daya', NULL, 'WIT', NULL, NULL),
  ('81.09', '81', 'KABUPATEN', 'Kabupaten Buru Selatan', NULL, 'WIT', NULL, NULL),
  ('81.71', '81', 'KOTA', 'Kota Ambon', 'Kota Ambon', 'WIT', NULL, NULL),
  ('81.72', '81', 'KOTA', 'Kota Tual', 'Kota Tual', 'WIT', NULL, NULL),
  ('82.01', '82', 'KABUPATEN', 'Kabupaten Halmahera Barat', NULL, 'WIT', NULL, NULL),
  ('82.02', '82', 'KABUPATEN', 'Kabupaten Halmahera Tengah', NULL, 'WIT', NULL, NULL),
  ('82.03', '82', 'KABUPATEN', 'Kabupaten Halmahera Utara', NULL, 'WIT', NULL, NULL),
  ('82.04', '82', 'KABUPATEN', 'Kabupaten Halmahera Selatan', NULL, 'WIT', NULL, NULL),
  ('82.05', '82', 'KABUPATEN', 'Kabupaten Kepulauan Sula', NULL, 'WIT', NULL, NULL),
  ('82.06', '82', 'KABUPATEN', 'Kabupaten Halmahera Timur', NULL, 'WIT', NULL, NULL),
  ('82.07', '82', 'KABUPATEN', 'Kabupaten Pulau Morotai', NULL, 'WIT', NULL, NULL),
  ('82.08', '82', 'KABUPATEN', 'Kabupaten Pulau Taliabu', NULL, 'WIT', NULL, NULL),
  ('82.71', '82', 'KOTA', 'Kota Ternate', 'Kota Ternate', 'WIT', NULL, NULL),
  ('82.72', '82', 'KOTA', 'Kota Tidore Kepulauan', 'Kota Tidore Kepulauan', 'WIT', NULL, NULL),
  ('91.03', '91', 'KABUPATEN', 'Kabupaten Jayapura', NULL, 'WIT', NULL, NULL),
  ('91.05', '91', 'KABUPATEN', 'Kabupaten Kepulauan Yapen', NULL, 'WIT', NULL, NULL),
  ('91.06', '91', 'KABUPATEN', 'Kabupaten Biak Numfor', NULL, 'WIT', NULL, NULL),
  ('91.10', '91', 'KABUPATEN', 'Kabupaten Sarmi', NULL, 'WIT', NULL, NULL),
  ('91.11', '91', 'KABUPATEN', 'Kabupaten Keerom', NULL, 'WIT', NULL, NULL),
  ('91.15', '91', 'KABUPATEN', 'Kabupaten Waropen', NULL, 'WIT', NULL, NULL),
  ('91.19', '91', 'KABUPATEN', 'Kabupaten Supiori', NULL, 'WIT', NULL, NULL),
  ('91.20', '91', 'KABUPATEN', 'Kabupaten Mamberamo Raya', NULL, 'WIT', NULL, NULL),
  ('91.71', '91', 'KOTA', 'Kota Jayapura', 'Kota Jayapura', 'WIT', NULL, NULL),
  ('92.02', '92', 'KABUPATEN', 'Kabupaten Manokwari', NULL, 'WIT', NULL, NULL),
  ('92.03', '92', 'KABUPATEN', 'Kabupaten Fak Fak', NULL, 'WIT', NULL, NULL),
  ('92.06', '92', 'KABUPATEN', 'Kabupaten Teluk Bintuni', NULL, 'WIT', NULL, NULL),
  ('92.07', '92', 'KABUPATEN', 'Kabupaten Teluk Wondama', NULL, 'WIT', NULL, NULL),
  ('92.08', '92', 'KABUPATEN', 'Kabupaten Kaimana', NULL, 'WIT', NULL, NULL),
  ('92.11', '92', 'KABUPATEN', 'Kabupaten Manokwari Selatan', NULL, 'WIT', NULL, NULL),
  ('92.12', '92', 'KABUPATEN', 'Kabupaten Pegunungan Arfak', NULL, 'WIT', NULL, NULL),
  ('93.01', '93', 'KABUPATEN', 'Kabupaten Merauke', NULL, 'WIT', NULL, NULL),
  ('93.02', '93', 'KABUPATEN', 'Kabupaten Boven Digoel', NULL, 'WIT', NULL, NULL),
  ('93.03', '93', 'KABUPATEN', 'Kabupaten Mappi', NULL, 'WIT', NULL, NULL),
  ('93.04', '93', 'KABUPATEN', 'Kabupaten Asmat', NULL, 'WIT', NULL, NULL),
  ('94.01', '94', 'KABUPATEN', 'Kabupaten Nabire', NULL, 'WIT', NULL, NULL),
  ('94.02', '94', 'KABUPATEN', 'Kabupaten Puncak Jaya', NULL, 'WIT', NULL, NULL),
  ('94.03', '94', 'KABUPATEN', 'Kabupaten Paniai', NULL, 'WIT', NULL, NULL),
  ('94.04', '94', 'KABUPATEN', 'Kabupaten Mimika', NULL, 'WIT', NULL, NULL),
  ('94.05', '94', 'KABUPATEN', 'Kabupaten Puncak', NULL, 'WIT', NULL, NULL),
  ('94.06', '94', 'KABUPATEN', 'Kabupaten Dogiyai', NULL, 'WIT', NULL, NULL),
  ('94.07', '94', 'KABUPATEN', 'Kabupaten Intan Jaya', NULL, 'WIT', NULL, NULL),
  ('94.08', '94', 'KABUPATEN', 'Kabupaten Deiyai', NULL, 'WIT', NULL, NULL)
ON CONFLICT (kode) DO NOTHING;

INSERT INTO public.kabupaten_kota (kode, provinsi_kode, tipe, nama, ibukota, zona_waktu, latitude, longitude) VALUES
  ('95.01', '95', 'KABUPATEN', 'Kabupaten Jayawijaya', NULL, 'WIT', NULL, NULL),
  ('95.02', '95', 'KABUPATEN', 'Kabupaten Pegunungan Bintang', NULL, 'WIT', NULL, NULL),
  ('95.03', '95', 'KABUPATEN', 'Kabupaten Yahukimo', NULL, 'WIT', NULL, NULL),
  ('95.04', '95', 'KABUPATEN', 'Kabupaten Tolikara', NULL, 'WIT', NULL, NULL),
  ('95.05', '95', 'KABUPATEN', 'Kabupaten Mamberamo Tengah', NULL, 'WIT', NULL, NULL),
  ('95.06', '95', 'KABUPATEN', 'Kabupaten Yalimo', NULL, 'WIT', NULL, NULL),
  ('95.07', '95', 'KABUPATEN', 'Kabupaten Lanny Jaya', NULL, 'WIT', NULL, NULL),
  ('95.08', '95', 'KABUPATEN', 'Kabupaten Nduga', NULL, 'WIT', NULL, NULL),
  ('96.01', '96', 'KABUPATEN', 'Kabupaten Sorong', NULL, 'WIT', NULL, NULL),
  ('96.02', '96', 'KABUPATEN', 'Kabupaten Sorong Selatan', NULL, 'WIT', NULL, NULL),
  ('96.03', '96', 'KABUPATEN', 'Kabupaten Raja Ampat', NULL, 'WIT', NULL, NULL),
  ('96.04', '96', 'KABUPATEN', 'Kabupaten Tambrauw', NULL, 'WIT', NULL, NULL),
  ('96.05', '96', 'KABUPATEN', 'Kabupaten Maybrat', NULL, 'WIT', NULL, NULL),
  ('96.71', '96', 'KOTA', 'Kota Sorong', 'Kota Sorong', 'WIT', NULL, NULL)
ON CONFLICT (kode) DO NOTHING;

COMMIT;
